version: '3'

services:
  api:
    container_name: wongames_api
    image: medeirospradoleonardo/wongames-api:latest
    environment:
     - DATABASE_HOST=d
     - DATABASE_PORT=5432
     - DATABASE_USERNAME=wongames
     - DATABASE_PASSWORD=wongames123
     - DATABASE_NAME=wongames123
     - STRIPE_KEY=pk_test_51L514jKp4ziTnOn0bGaES0qYi95Iyv31Df753FWPcM28GduZevVTTb6SEUq9B90s3FpvbE68klLRxea8pjl5R4Zi00v4uuPsxM
    ports:
      - '1337:1337'
    depends_on:
      - db

  db:
    container_name: wongames_db
    image: medeirospradoleonardo/database-wongames:latest
    ports:
      - '5432:5432'